# Execute 'make check' with dependencies on linux
# Execute 'make check' with dependencies on macos
# Execute 'make check' with dependencies on freebsd
# Execute 'make check' with dependencies on redox
# Execute 'make check' with dependencies on windows

container:
  image: node:latest

task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install

  matrix:
    - name: Lint
      lint_script: yarn run lint
    - name: Test
      container:
        matrix:
          - image: node:latest
          - image: node:lts
      test_script: yarn run test
