image: gitpod/workspace-full:latest

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true

# Each '-' under 'tasks' corresponds to a separete terminal
tasks:
  # Prebuild deps
  - init: apt-get update && apt-get install -y meson cppcheck libcap-dev clang libfuse3-dev gcc git ninja-build bison libtool autoconf pkg-config libcap-dev indent fakeroot libattr1-dev uthash-dev gzip rsync autopoint uthash-dev shellcheck && wget https://github.com/mvdan/sh/releases/download/v3.0.0-beta1/shfmt_v3.0.0-beta1_linux_amd64 -O /usr/bin/shfmt && chmod +x /usr/bin/shfmt

vscode:
  extensions:
    - timonwong.shellcheck@0.8.1:16BMw7Jrwd/KkAhJrkHwqQ==