#!/bedrock/libexec/busybox sh
# shellcheck shell=sh
# Copyright 2019 Jacob Hrbek <kreyren@rixotstudio.cz>
# Distributed under the terms of the GNU General Public License v3 (https://www.gnu.org/licenses/gpl-3.0.en.html) or later
# Based in part upon 'brl-disable' from Bedrock Linux (https://github.com/bedrocklinux/bedrocklinux-userland/blob/master/src/slash-bedrock/libexec/brl-disable), which is:
# 		Copyright 2016-2019 Daniel Thau <danthau@bedrocklinux.org> as GPLv2

# De-integrates strata from the system (FIXME, more info)

# shellcheck source=src/slash-bedrock/lib/shell/common-code.sh
. /bedrock/lib/shell/common-code.sh

print_help() {
	printf '%s\n' "Usage: ${color_cmd}brl disable ${color_sub}[options] <strata>${color_norm}

De-integrates ${color_term}strata${color_norm} from the system.

Options:
  ${color_cmd}-h${color_norm}, ${color_cmd}--help${color_norm}   print this message

Examples:
  ${color_cmd}$ brl status solus
  ${color_strat}solus${color_norm}: ${color_okay}enabled
  ${color_rcmd}# brl disable solus
  ${color_cmd}$ brl status solus
  ${color_norm}disabled
  ${color_rcmd}# brl disable alpine arch centos
  ${color_cmd}$ brl status alpine arch centos
  ${color_strat}alpine${color_norm}: ${color_norm}disabled
  ${color_strat}arch${color_norm}: ${color_norm}disabled
  ${color_strat}centos${color_norm}: ${color_norm}disabled
${color_norm}"
}

handle_help "${@:-}"
min_args "${#}" "1"

require_root
lock

for alias in "${@}"; do
	if ! is_stratum_or_alias "${alias}"; then
		abort "No stratum or alias called \"${stratum}\"."
	elif ! stratum="$(deref "${alias}")"; then
		abort "Unable to dereference \"${alias}\"."
	elif is_init "${stratum}"; then
		abort "Cannot disable init-providing stratum."
	elif is_bedrock "${stratum}"; then
		abort "Cannot disable bedrock stratum."
	else
		disable_stratum "${stratum}"
	fi
done

die 0
