#!/bin/sh
# Copyright 2019 Jacob Hrbek <kreyren@rixotstudio.cz>
# Distributed under the terms of the GNU General Public License v3 (https://www.gnu.org/licenses/gpl-3.0.en.html) or later
# Based in part upon 'brl-deref' from Bedrock Linux (https://github.com/bedrocklinux/bedrocklinux-userland/blob/master/src/slash-bedrock/libexec/brl-deref), which is:
# 		Copyright 2016-2019 Daniel Thau <danthau@bedrocklinux.org> as GPLv2

# Dereference stratum aliases (FIXME, more info)

# shellcheck source=src/slash-bedrock/lib/shell/common-code.sh
. /bedrock/lib/shell/common-code.sh

print_help() {
	printf '%s\n' "Usage: ${color_cmd}brl deref ${color_sub}[options] <strata>${color_norm}

Dereferences ${color_term}aliases${color_norm}.  Dereferencing a non-${color_term}alias${color_norm} ${color_term}stratum${color_norm} returns the ${color_term}stratum${color_norm}.

Options:
  ${color_cmd}-h${color_norm}, ${color_cmd}--help${color_norm}   print this message

Example:
  ${color_rcmd}# brl fetch fedora --release 27 --name fedora27
  ${color_rcmd}# brl fetch debian --release unstable --name sid
  ${color_rcmd}# brl alias fedora27 fedora
  ${color_rcmd}# brl alias sid unstable
  ${color_cmd}$ brl deref fedora
  ${color_strat}fedora27
  ${color_cmd}$ brl deref fedora27
  ${color_strat}fedora27
  ${color_cmd}$ brl deref unstable
  ${color_strat}sid
  ${color_cmd}$ brl deref sid
  ${color_strat}sid
${color_norm}"
}

handle_help "${@:-}"
min_args "${#}" "1"

for alias in "${@}"; do
	if ! is_stratum_or_alias "${alias}"; then
		abort "No stratum or alias called \"${alias}\"."
	elif ! stratum="$(deref "${alias}")"; then
		abort "Unable to dereference \"${alias}\"."
	else
		printf "${color_strat}%s${color_norm}\\n" "${stratum}"
	fi
done

die 0
